name: RSS to Telegram
on:
  schedule:
    # ① 9:30-22:00 GMT+8 → UTC 1:30-14:00，每5分钟一次
    - cron: "30-59/5 1-13 * * *"  # UTC 1:30,1:35,...,13:55
    - cron: "0-29/5 14 * * *"    # UTC 14:00,14:05,...,14:29

    # ② 22:00-0:00 GMT+8 → UTC 14:00-16:00，每小时一次
    - cron: "0 14-15 * * *"      # UTC 14:00,15:00

    # ③ 7:00-9:30 GMT+8 → UTC 23:00-1:30，每小时一次
    - cron: "0 23 * * *"         # UTC 23:00
    - cron: "0 0 * * *"          # UTC 0:00
    - cron: "0 1 * * *"          # UTC 1:00

  workflow_dispatch:  # 允许手动触发

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 设置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: pip install python-telegram-bot feedparser

      - name: 运行脚本
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          RSS_URL: ${{ secrets.RSS_URL }}
        run: python rss_pusher.py

      - name: 提交更新后的ID文件
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "更新已发送的帖子ID"
          file_pattern: "sent_posts.json"
          branch: main
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
